name: StrikeExtraPlaceholders
version: '${project.version}'
main: dev.iiahmed.sep.StrikeExtraPlaceholders
depend: [ StrikePractice, PlaceholderAPI ]
authors: [ iiAhmedYT ]
description: An additional Placeholders system for StrikePractice
website: https://iiahmed.dev
commands:
  SEP:
    description: the StrikeExtraPlaceholders command
  quickranked:
    description: Быстрый поиск - закидывает в очередь где уже есть игрок
    aliases: [qr]
  queuenotify:
    description: Включить/выключить уведомления о поиске матчей
    aliases: [qn, queuealert]
